### ISSUE TITLE
MobX 4.0.0 Support

### ISSUE THREAD

**Issue by Tresky** [nighca/movue#20]
I have been using Movue for a little while now with no problems. I recently updated to MobX 4.0.0 and haven't run into a real issue yet, but a deprecation notice has been popping up in Movue since the update warning a feature being changed.

In MobX 4.0.0, the library is abandoning positional arguments in favor of named arguments. See this function on line 32 of `Movue/src/change-detector.ts`.

```javascript
defineReactionList(vm: VueClass, fromMobxEntries: FromMobxEntry[]) {
  const reactivePropertyListKey = this._getReactionListKey(vm)
  const reactivePropertyList: Disposer[] = fromMobxEntries.map(({ key, get }) => {
    const updateReactiveProperty = value => { this.updateReactiveProperty(vm, key, value) }

    // Changed positional argument to named argument
    // OLD: return this.mobxMethods.reaction(() => get.call(vm), updateReactiveProperty, true)
    return this.mobxMethods.reaction(() => get.call(vm), updateReactiveProperty, { fireImmediately: true })
  })

  this.changeDetector[reactivePropertyListKey] = reactivePropertyList
}
```

[See this clip from the MobX 4.0.0 Change Log.](https://imgur.com/a/hOcu5)

This is the only issue I have found since upgrading to MobX 4.0.0, but will report if I find more. This fix is extraordinarily easy. If I get some free time before this gets patched in, I will submit a pull request, myself. Not sure how much time I'll have soon though.

Great work on this little plugin!
Tresky

**Comment by nighca** [comment]
Thanks for your report, I will fix it!

**Comment by nighca** [comment]
@Tresky Plz try movue v0.2.1.
