### ISSUE TITLE
在Mobx中定义的数组该如何在Vue中更新？

### ISSUE THREAD

**Issue by xiaobebe** [nighca/movue#23]
感谢作者的贡献！

在我们的项目中已经完全使用mobx代替了vuex，并使用了movue，使用过程中发现了不少问题。

首先我想知道我在Mobx中定义的集合，数组该如何在Vue中得到相应呢。

```
class RenderImgData {
  @observable renderList = [];
}
```

```
 fromMobx:{
      watchImgs(){
        var imgs = RenderData.renderImgs;
}
```
当我在renderList中push元素，发现在vue中并没有得到相应。请问如何能解决这种问题呢

**Comment by nighca** [comment]
跟 #19 这里说到的应该是一个问题哈，可以参考下
