### ISSUE TITLE
support vue-devtool

### ISSUE THREAD

**Issue by nighca** [nighca/movue#6]
Simulate the [events](https://github.com/vuejs/vuex/blob/master/src/plugins/devtool.js)，so we can use vue-devtool to debug our app.

**Comment by jwkicklighter** [comment]
With the launch of the new devtools that support plugins, this could be easier to accomplish

**Comment by nighca** [comment]
@jwkicklighter Yeah, you are right. But this project is not meant to be maintained any longer. Thanks for the suggestion, anyway.
